config/routes.rb
Rails.application.routes.draw do
  # resources :months
  devise_for :players, controllers: {
    registrations: 'players/registrations'
  }
  resources :players
  resources :gladiators
  resources :competitions
  resources :posts
  # resources :months
  devise_for :admins
  get 'pages/home'
  get 'pages/about'
  get '/about', to: "pages#about"
  get '/ranklist', to: "pages#ranklist"
  get '/old', to: "pages#home"
  root to: 'pages#home'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :admin
end

app/models/gladiator.rb
class Gladiator < ApplicationRecord
  belongs_to :admin
  has_many :players_in_tour
  has_many :players, through: :players_in_tour
  has_many :points

  def status
    return 'В игра....' if start_date == Date.today
    return 'Завършил'   if start_date < Date.today
    return 'Предстоящ'  if start_date > Date.today
  end
end

app/models/mesecen_tour.rb
class MesecenTour < ApplicationRecord
  belongs_to :admin
end

app/models/month.rb
class Month < ApplicationRecord
  belongs_to :admin

  def status
    return 'В игра....' if start_date == Date.today
    return 'Завършил'   if start_date < Date.today
    return 'Предстоящ'  if start_date > Date.today
  end  
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :players_in_tour, dependent: :destroy
  has_many :gladiators, through: :players_in_tour

  attr_accessor :points, :enrolled

  def enrolled_in?(tour)
    PlayersInTour.where(player: self, gladiator: tour).present?
  end

  def points_for(tour)
    PlayersInTour.find_by(player: self, gladiator: tour).points
  end
end

app/models/players_in_tour.rb
class PlayersInTour < ApplicationRecord
  belongs_to :player
  belongs_to :gladiator
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :player
  belongs_to :gladiator
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/gladiators_controller.rb
class GladiatorsController < ApplicationController
  before_action :set_gladiator, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show, :index]
  # GET /gladiators
  # GET /gladiators.json
  def index
    @gladiators = Gladiator.order(start_date: :desc)
  end

  # GET /gladiators/1
  # GET /gladiators/1.json
  def show
    @players = Player.all
  end

  # GET /gladiators/new
  def new
    @gladiator = Gladiator.new
  end

  # GET /gladiators/1/edit
  def edit
  end

  # POST /gladiators
  # POST /gladiators.json
  def create
    @gladiator = Gladiator.new(gladiator_params)
    @gladiator.admin = current_admin
    respond_to do |format|
      if @gladiator.save
        format.html { redirect_to @gladiator, notice: 'Gladiator was successfully created.' }
        format.json { render :show, status: :created, location: @gladiator }
      else
        format.html { render :new }
        format.json { render json: @gladiator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gladiators/1
  # PATCH/PUT /gladiators/1.json
  def update
    @players = Player.where(activated: true)
    respond_to do |format|
      if @gladiator.update(gladiator_params)
        format.html { redirect_to @gladiator, notice: 'Gladiator was successfully updated.' }
        format.json { render :show, status: :ok, location: @gladiator }
      else
        format.html { render :edit }
        format.json { render json: @gladiator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gladiators/1
  # DELETE /gladiators/1.json
  def destroy
    @gladiator.destroy
    respond_to do |format|
      format.html { redirect_to gladiators_url, notice: 'Gladiator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gladiator
      @gladiator = Gladiator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gladiator_params
      params.require(:gladiator).permit(:title, :start_date, :info, player_ids: [])
    end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  before_action :set_month, only: [:show, :edit, :update, :destroy]

  # GET /months
  # GET /months.json
  def index
    @months = Month.all
  end

  # GET /months/1
  # GET /months/1.json
  def show
  end

  # GET /months/new
  def new
    @month = Month.new
  end

  # GET /months/1/edit
  def edit
  end

  # POST /months
  # POST /months.json
  def create
    @month = Month.new(month_params)

    respond_to do |format|
      if @month.save
        format.html { redirect_to @month, notice: 'Month was successfully created.' }
        format.json { render :show, status: :created, location: @month }
      else
        format.html { render :new }
        format.json { render json: @month.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /months/1
  # PATCH/PUT /months/1.json
  def update
    respond_to do |format|
      if @month.update(month_params)
        format.html { redirect_to @month, notice: 'Month was successfully updated.' }
        format.json { render :show, status: :ok, location: @month }
      else
        format.html { render :edit }
        format.json { render json: @month.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /months/1
  # DELETE /months/1.json
  def destroy
    @month.destroy
    respond_to do |format|
      format.html { redirect_to months_url, notice: 'Month was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_month
      @month = Month.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def month_params
      params.require(:month).permit(:title, :description, :start_date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin!, except: [:help, :about, :home]

  def home
  end

  def about
  end

  def ranking

    @players = Player.all
    @gladiators = Gladiator.all

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/gladiators_helper.rb
module GladiatorsHelper
end

app/helpers/mesecen_tours_helper.rb
module MesecenToursHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/gladiators/_form.html.erb
<%= bootstrap_form_with(model: gladiator) do |form| %>
  <% if gladiator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gladiator.errors.count, "error") %> prohibited this gladiator from being saved:</h2>

      <ul>
        <% gladiator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.text_field :title %>

    <%= form.datetime_select :start_date %>

    <%= form.text_area :info %>
  <!-- </div> -->
  <br>

    <%= form.submit %>
<% end %>

app/views/gladiators/edit.html.erb
<section class="breadcrumbs">
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2>Лига "Гладиатори"</h2>
      <ol>
        <li><a href="index.html">Home</a></li>
        <li>Gladiators</li>
      </ol>
    </div>

  </div>
</section>

<%= render 'form', gladiator: @gladiator %>

<%= link_to 'Show', @gladiator %> |
<%= link_to 'Back', gladiators_path %>

app/views/gladiators/index.html.erb
<br>

<main id="main" data-aos="fade-up">

  <!-- ======= Breadcrumbs ======= -->
  <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Лига "Гладиатори"</h2>
        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Gladiators</li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs -->

  <section class="inner-page">
    <div class="container">
      <p>
        Сезон 2021
      </p>
    </div>
  </section>

  <div class="container">

      <table class="table table-striped">
        <thead class="thead-light">
          <tr>
            <th scope="col" class= "text-center">#</th>
            <th scope="col" class= "text-center">Име на турнир:</th>
            <th scope="col" class= "text-center">Начална дата:</th>
            <th scope="col" class= "text-center">Статус:</th>
            <%- if admin_signed_in? %>
              <th scope="col"></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @gladiators.each.with_index(1) do |gladiator, i| %>
            <tr>
              <th scope="row" class= "text-center"><%= i %></th>
              <td class= "text-center"><%= link_to gladiator.title, gladiator %></td>
              <td class= "text-center"><%= gladiator.start_date.strftime('%d-%b-%Y  | %H:%Mч.') %></td>
              <td class= "text-center"><b><%= gladiator.status%></b></td>

              <%- if admin_signed_in? %>
                <td><%= link_to 'Destroy', gladiator, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <% if current_admin %>
        <%= link_to 'Създай нов гладиатор', new_gladiator_path, class: 'btn btn-secondary' %>
      <% end %>
      </div>
      <br>
  </main>

app/views/gladiators/new.html.erb
<section class="breadcrumbs">
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2>Лига "Гладиатори"</h2>
      <ol>
        <li><a href="index.html">Home</a></li>
        <li>Gladiators</li>
      </ol>
    </div>

  </div>
</section>

<%= render 'form', gladiator: @gladiator %>

<%= link_to 'Back', gladiators_path %>

app/views/gladiators/show.html.erb
<section class="breadcrumbs">
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2>Лига "Гладиатори"</h2>
      <ol>
        <li><a href="index.html">Home</a></li>
        <li>Gladiators</li>
      </ol>
    </div>

  </div>
</section>

<div class="container">
  <p id="notice"><%= notice %></p>

  <div class='tour-details text-center'>
    <h5>
      <%= "Tournament #{@gladiator.title} starts at: #{@gladiator.start_date.strftime('%d-%b-%Y  | %H:%Mч.')} (admin: #{@gladiator.admin.email})" %>
    </h5>

    <%- if admin_signed_in? %>
      <%= link_to 'Edit', edit_gladiator_path(@gladiator), class: 'btn btn-primary' %>
    <% end %>

    <p>
    <strong>Description:</strong>
    <%= @gladiator.info %>
    </p>

  </div>

  <div class='tour-enrollment text-center'>
    <hr>
    <div class="table">
      <h3>
        <caption><%="Players enrolled: #{@gladiator.players.count}" %></caption>
      </h3>
      <%= form_for @gladiator do |f| %>
        <table class="table table-striped">
          <thead class="thead-dark">
            <tr>
              <th>Player:</th>
              <th>Enrolled?</th>
            </tr>
          </thead>
          <tbody>
            <%- if admin_signed_in? %>
              <%= f.collection_check_boxes :player_ids, @players, :id, :name, custom: :switch  do |b| %>
                <tr>
                  <td><%= b.label %></td>
                  <td><%= b.check_box %></td>
                </tr>
              <% end %>
            <% end %>
            <%- unless admin_signed_in? %>
              <% @gladiator.players.each do |player| %>
                <tr>
                  <td><%= player.name %></td>
                  <td>Enrolled</td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <%- if admin_signed_in? %>
          <div class="form-actions">
            <%= f.submit %>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>