config/routes.rb
Rails.application.routes.draw do
  # resources :months
  devise_for :players, controllers: {
    registrations: 'players/registrations'
  }
  resources :players
  resources :gladiators
  resources :competitions
  resources :posts
  # resources :months
  devise_for :admins
  get 'pages/home'
  get 'pages/about'
  get '/about', to: "pages#about"
  get '/ranklist', to: "pages#ranklist"
  get '/old', to: "pages#home"
  root to: 'pages#home'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :admin
end

app/models/gladiator.rb
class Gladiator < ApplicationRecord
  belongs_to :admin
  has_many :players_in_tour
  has_many :players, through: :players_in_tour
  has_many :points

  def status
    return 'В игра....' if start_date == Date.today
    return 'Завършил'   if start_date < Date.today
    return 'Предстоящ'  if start_date > Date.today
  end
end

app/models/mesecen_tour.rb
class MesecenTour < ApplicationRecord
  belongs_to :admin
end

app/models/month.rb
class Month < ApplicationRecord
  belongs_to :admin

  def status
    return 'В игра....' if start_date == Date.today
    return 'Завършил'   if start_date < Date.today
    return 'Предстоящ'  if start_date > Date.today
  end  
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :players_in_tour, dependent: :destroy
  has_many :gladiators, through: :players_in_tour

  attr_accessor :points, :enrolled

  def enrolled_in?(tour)
    PlayersInTour.where(player: self, gladiator: tour).present?
  end

  def points_for(tour)
    PlayersInTour.find_by(player: self, gladiator: tour).points
  end
end

app/models/players_in_tour.rb
class PlayersInTour < ApplicationRecord
  belongs_to :player
  belongs_to :gladiator
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :player
  belongs_to :gladiator
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin!, except: [:help, :about, :home]

  def home
  end

  def about
  end

  def ranking

    @players = Player.all
    @gladiators = Gladiator.all

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/gladiators_helper.rb
module GladiatorsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_adsense.html.erb
<script data-ad-client="ca-pub-8041370207584636" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-KH22N7DBM0"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-KH22N7DBM0');
</script>

app/views/layouts/_cookies.html.erb
<!-- https://cookieinfoscript.com/ -->

<script type="text/javascript" id="cookieinfo"
	src="//cookieinfoscript.com/js/cookieinfo.min.js"
  data-message="Бисквитки. Чрез тях ние успяваме да получим информация относно трафика на уебсайтовете ни и се стремим към подобрение. Бидейки тук, вие се съгласявате с условията им."
  data-linkmsg="Прочетете повече за тях."
  data-moreinfo="https://policies.google.com/technologies/cookies?hl=bg"
  data-close-text="Приемам!">
</script>

app/views/layouts/_footer.html.erb
<footer id="footer">

  <div class="footer-newsletter">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6">
          <h4>Реклама</h4>
          <!-- <p></p> -->
          <!-- <form action="" method="post">
            <input type="email" name="email"><input type="submit" value="Subscribe">
          </form> -->
        </div>
      </div>
    </div>
  </div>

  <div class="footer-top">
    <div class="container">
      <div class="row">

        <div class="col-lg-3 col-md-6 footer-contact">
          <h3><span>Tennis</span>Burgas<span>.com</span></h3>
          <p class = "text-center">
            --- <br>
            Бургас, България<br>
            <br>
            <strong>Phone:</strong> +359 000 000 000<br>
            <strong>Email:</strong> contact@tennisburgas.com<br>
          </p>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Навигация</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="/#hero">Начало</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="/#about">За нас</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="/#tours">Турнири</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="/gladiators">Лига Гладиатори</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="/months">Месечен Турнир</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="/#contact">Контакти</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Социални Мрежи</h4>
          <div class="social-links mt-3">
            <a href="#" class="twitter"><i class="fab fa-facebook"></i></a>
            <a href="#" class="twitter"><i class="fab fa-instagram"></i></a>
            <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
            <a href="#" class="twitter"><i class="fab fa-github"></i></a>

          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Админ достъп</h4>
          <p></p>

          <%- if current_admin %>
            <%= link_to "Log out", destroy_admin_session_path, method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to 'Логин', new_admin_session_path, class: 'btn btn-success'%>
           <% end %>
        </div>

      </div>
    </div>
  </div>

  <div class="container py-4">

    <div class="copyright">
      &copy; Авторско Право <strong><span>TennisBurgas.com</span></strong>. Всички Права Запазени!
      <br>
      &copy; Copyright <strong><span>TennisBurgas.com</span></strong>. All Rights Reserved!
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bizland-bootstrap-business-template/ -->
      <br>
      FullStack development by <a href="https://bootstrapmade.com/">BraTac.net</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar-tailwind.html.erb
<br>
<br>
<br>
<br>


<button type="button" className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150">

app/views/layouts/_navbar.html.erb
<div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
  <div class="container d-flex">
    <div class="contact-info mr-auto">
      <i class="fas fa-at"></i> <a href="mailto:contact@example.com">contact@tennisburgas.com</a>
      <i class="fas fa-phone-alt"></i> +359 000 000 000
      <i class="fas fa-code"></i> FullStack Development by Bratac.net
    </div>
    <div class="social-links">
      <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
      <a href="#" class="facebook"><i class="fab fa-facebook"></i></a>
      <a href="#" class="instagram"><i class="fab fa-instagram"></i></a>
      <a href="#" class="skype"><i class="fab fa-skype"></i></a>
      <a href="#" class="linkedin"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>
</div>

<!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
  <div class="container d-flex align-items-center">

    <h1 class="logo mr-auto"><a href="/">TennisBurgas<span>.com</span></a></h1>
    <!-- Uncomment below if you prefer to use an image logo -->
    <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt=""></a>-->

    <nav class="nav-menu d-none d-lg-block">
      <ul>
        <li class="active"><a href="/#hero">Начало</a></li>
        <li><a href="#about">За Нас</a></li>
        <!-- <li><a href="#tours">Турнири</a></li> -->
        <li class="drop-down"><a href="/#tours">Турнири <i class="fas fa-caret-down"></i></a>
          <ul>
            <li><a href="/gladiators">Лига "Гладиатори"</a></li>
            <!-- <li class="drop-down"><a href="#">Deep Drop Down</a>
              <ul>
                <li><a href="#">Deep Drop Down 1</a></li>
                <li><a href="#">Deep Drop Down 2</a></li>
                <li><a href="#">Deep Drop Down 3</a></li>
                <li><a href="#">Deep Drop Down 4</a></li>
                <li><a href="#">Deep Drop Down 5</a></li>
              </ul>
            </li> -->
            <li><a href="/months">Месечен Турнир</a></li>
            <li><a href="#">Класиране</a></li>

          </ul>
        </li>
        <li><a href="/#contact">Контакти</a></li>


      </ul>
    </nav><!-- .nav-menu -->

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Център за Тенис на Маса гр. Бургас</title>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" type="image/jpg" href="img/favicon.ico"/>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# stylesheet_link_tag 'footer', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.2.2/web-animations.min.js"></script>
    <%= render 'layouts/analytics' %>
    <%= render 'layouts/adsense' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%# <%= render 'layouts/alerts' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    <%# render 'layouts/cookies' %>
    </body>
</html>

app/views/pages/ranking.html.erb
<section class="breadcrumb-area bg-img bg-overlay jarallax" style="background-image: url(<%= asset_path 'tour2.jpg' %>);">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12">
        <div class="breadcrumb-content">
          <h2>Ranking</h2>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"> <%=link_to 'Начало', root_path %></li>
              <li class="breadcrumb-item active" aria-current="page">Ranking</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
</section>

<p id="notice"><%= notice %></p>




<div class="limiter">
  <div class="container">
    <ul class="responsive-table">
      <h5 class="gladiators-info"></h5>
      <br>
      <h2> Сезон 2021 </h2>


      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Points</th>
          </tr>
        </thead>
        <tbody>
          <% @players.each.with_index(1) do |player, i| %>
            <tr>
              <th scope="row"><%= i %></th>
              <td><%= link_to player.name, player %></td>
              <td>Точки</td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>


  </div>
</div>